### ISSUE TITLE
Option to load unknown mods last instead of removing them

### ISSUE THREAD

**Issue by Nightliss** [shakeyourbunny/RWMS#13]
Hey @shakeyourbunny , can you add an ini option or y/n after load order has been sorted to leave unknown mods enabled. I have some few personal tweaks and enabling them each time after I add mod takes too much time on >200 modlist :)

**Comment by Thirsk** [comment]
You can use Mehni's [ModSorter](https://github.com/Mehni/ModSorter/) to solve your problem. It doesn't automatically sort mods like RWMS, it's just an external tool to let you sort them yourself. I highly recommend using the two together.

**Comment by shakeyourbunny** [comment]
Well, it's an option to consider to let the mods be via an configuration option.

The sorting method RWMS uses, is destructive, it tosses away the current mod order and then rebuilds it akin to the categories, leaving out the unknown ones. 

There could be the possibility just to stick the unknown mods at the bottom of the order list, but if I add some support of tweaking file to modify the load order afterwards in addition, would be some idea.

> ; -- rwms_config.ini --
> ; do not delete unknown mods if True, stick them at the end of the load order.
> dontremoveunknown = False

Tweak support would be split in two files: 
- **rwms_tweaks.ini** contains tweaks shipped with RWMS, common load chains which cannot be implemented via the category system.
- **rwms_tweaks_personal.ini** contains personal, not tracked tweaks

Commands for tweaks:
**loadbefore mod1 mod2**: load mod2 (directly) BEFORE mod1
**loadafter mod1 mod2**: load mod2 (directly) AFTER mod1
**loadfirst mod1**: first mod to load (Core is ignored (*))
**loadlast mod1**:  put mod at the bottom of the load order
**cloadbefore category mod**: load mod before category category
**cloadafter category mod**: load mod after category category

(*) if you wish to load something directly after Core, use "loadafter Core HugsLib" (for example)
If there is "loadafter Core mod1", "loadafter Core mod2", load order is "Core -> mod2 -> mod1".

Are these tweak commands enough?

I want to keep the tweaks simple, because the main focus should remain in the database and not having a  massive tweaks file for doing the job. With these commands you will be able to form your own load chains though.

NB: the tweaks would be applied AFTER sorting.

What do you think?

**Comment by shakeyourbunny** [comment]
> You can use Mehni's [ModSorter](https://github.com/Mehni/ModSorter/) to solve your problem. It doesn't automatically sort mods like RWMS, it's just an external tool to let you sort them yourself. I highly recommend using the two together.

Interesting that Mehni wrote such a sort application, would be neat to have a "sort" button there which in turn let RWMS run.

**Comment by Nightliss** [comment]
Looks fine to me!

**Comment by shakeyourbunny** [comment]
added https://github.com/shakeyourbunny/RWMS/releases/tag/0.94.3 which includes a configuration switch (and new command line stuff) for keeping unknown mods in the list. Due to aforementioned reason, they will be sticked at the bottom of the mod list.

> usage: rwms_sort.py [-h] [--disable-steam] [--dont-remove-unknown-mods]
>                    [--contributors] [--reset-to-core]
>
>optional arguments:
>  -h, --help            show this help message and exit
>  --disable-steam       force disable steam detection
>  --dont-remove-unknown-mods
>                        do not remove unknown mods
>  --contributors        display all contributors to RWMS(DB)
>  --reset-to-core       reset mod list to Core only

Oh, and I took the liberty to shamelessly implement the "reset to core" button of Mehni's ModSorter in RWMS as a command line switch :-)

Tweaks stuff will come in the next days or week, this is a rather bigger rewrite to support this.

**Comment by shakeyourbunny** [comment]
oh sorry, was fixed long ago ;D
